import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} app-shell`}>
        <header className="app-header">
          <div className="app-header-inner">
            <div className="app-title">
              <span className="app-logo-pill" />
              <div>
                <div>Recruit Tracker</div>
                <div className="app-subtitle">
                  내 지원 현황을 한 눈에 정리하는 개인용 대시보드
                </div>
              </div>
            </div>
            <span className="badge-tag">
              <span className="badge-dot" />
              Personal tool
            </span>
          </div>
        </header>
        <main className="app-main">{children}</main>
      </body>
    </html>
  );
}
